# Dataset download links configuration
# This file contains download URLs and metadata for datasets used in this project

# Data storage paths configuration
paths:
  datasets: "data/data"              # Path for datasets (download_dataset.py)
  homology_databases: "data/homology_databases"  # Path for homology databases (download_homology_databases.py)

datasets:
  esm2_contact_prediction:
    name: "ESM2 Contact Prediction Dataset"
    url: "https://drive.usercontent.google.com/download?id=1DkSXd_3mqQ1eJxOGUfAw0TMcS9ZEuouf&export=download&authuser=0"
    description: "Dataset for ESM2 protein contact prediction training"
    file_format: "zip"
    expected_size_gb: ~2.0

# Homology database configuration
# This section contains download URLs and metadata for HHblits homology search databases
homology_databases:
  base_path: "data/homology_databases"  # Default local storage path

  pdb70:
    name: "PDB70 Structural Templates"
    filename: "pdb70_from_mmcif_220313.tar.gz"
    url: "https://wwwuser.gwdguser.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/pdb70_from_mmcif_220313.tar.gz"
    compressed_size_gb: 27
    extracted_size_gb: 56
    extract_to: "pdb70"
    path: "data/homology_databases/pdb70"  # Explicit path to database directory
    database_name: "pdb70"  # Name prefix for database files
    description: "PDB70 structural templates (70% identity clustering)"
    database_files:
      - "pdb70_a3m.ffdata"
      - "pdb70_a3m.ffindex"
      - "pdb70_cs219.ffdata"
      - "pdb70_cs219.ffindex"
      - "pdb70_hhm.ffdata"
      - "pdb70_hhm.ffindex"

  uniref30:
    name: "UniRef30 Sequence Homologs"
    filename: "UniRef30_2023_02_hhsuite.tar.gz"
    url: "https://wwwuser.gwdguser.de/~compbiol/uniclust/2023_02/UniRef30_2023_02_hhsuite.tar.gz"
    compressed_size_gb: 66
    extracted_size_gb: 218
    extract_to: "UniRef30_2023_02_hhsuite"
    path: "data/homology_databases/UniRef30_2023_02_hhsuite"  # Explicit path to database directory
    database_name: "UniRef30_2023_02_hhsuite"  # Name prefix for database files
    description: "UniRef30 sequence homologs (30% identity clustering)"
    database_files:
      - "UniRef30_2023_02_hhsuite_a3m.ffdata"
      - "UniRef30_2023_02_hhsuite_a3m.ffindex"
      - "UniRef30_2023_02_hhsuite_cs219.ffdata"
      - "UniRef30_2023_02_hhsuite_cs219.ffindex"
      - "UniRef30_2023_02_hhsuite_hhm.ffdata"
      - "UniRef30_2023_02_hhsuite_hhm.ffindex"

# Template search configuration
template_search:
  # Quality thresholds for TemplateSearcher (strict parameters)
  quality_thresholds:
    min_sequence_identity: 0.18    # 18% minimum sequence identity (literature-optimal)
    min_coverage: 0.6            # 60% minimum coverage (good structural coverage)
    max_e_value: 1e-3           # Standard E-value threshold

  # Fallback quality thresholds (relaxed parameters)
  fallback_quality_thresholds:
    min_sequence_identity: 0.10    # 10% minimum sequence identity (relaxed)
    min_coverage: 0.4            # 40% minimum coverage (relaxed)
    max_e_value: 1e-2           # Less strict E-value threshold

  # HHblits parameters for different database types
  hhblits_parameters:
    pdb70:
      e_value: "1e-3"           # Standard E-value for structural templates
      coverage: "0.6"           # Good coverage requirement for structural templates
      max_sequences: "3000"     # Balanced diversity and quality
      iterations: "3"
    uniref30:
      e_value: "1e-3"           # Standard E-value for sequence homologs
      coverage: "0.5"           # Good coverage for sequence homologs
      max_sequences: "5000"     # More sequence diversity for homologs
      iterations: "3"

  # General search settings
  max_templates: 20             # Maximum number of templates to process
  cpu_limit: 2                 # Maximum CPU cores to use