# Dataset download links configuration
# This file contains download URLs and metadata for datasets used in this project

# Data storage paths configuration
paths:
  datasets: "data/data"              # Path for datasets (download_dataset.py)
  homology_databases: "data/homology_databases"  # Path for homology databases (download_homology_databases.py)

datasets:
  esm2_contact_prediction:
    name: "ESM2 Contact Prediction Dataset"
    url: "https://drive.usercontent.google.com/download?id=1DkSXd_3mqQ1eJxOGUfAw0TMcS9ZEuouf&export=download&authuser=0"
    description: "Dataset for ESM2 protein contact prediction training"
    file_format: "zip"
    expected_size_gb: ~2.0

# Homology database configuration
# This section contains download URLs and metadata for HHblits homology search databases
homology_databases:
  base_path: "data/homology_databases"  # Default local storage path

  pdb70:
    name: "PDB70 Structural Templates"
    filename: "pdb70_from_mmcif_220313.tar.gz"
    url: "https://wwwuser.gwdguser.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/pdb70_from_mmcif_220313.tar.gz"
    compressed_size_gb: 27
    extracted_size_gb: 56
    extract_to: "pdb70"
    description: "PDB70 structural templates (70% identity clustering)"
    database_files:
      - "pdb70_a3m.ffdata"
      - "pdb70_a3m.ffindex"
      - "pdb70_hhm.ffdata"
      - "pdb70_hhm.ffindex"

  uniref30:
    name: "UniRef30 Sequence Homologs"
    filename: "UniRef30_2023_02_hhsuite.tar.gz"
    url: "https://wwwuser.gwdguser.de/~compbiol/uniclust/2023_02/UniRef30_2023_02_hhsuite.tar.gz"
    compressed_size_gb: 66
    extracted_size_gb: 218
    extract_to: "UniRef30_2023_02_hhsuite"
    description: "UniRef30 sequence homologs (30% identity clustering)"
    database_files:
      - "UniRef30_2023_02_a3m.ffdata"
      - "UniRef30_2023_02_a3m.ffindex"
      - "UniRef30_2023_02_hhm.ffdata"
      - "UniRef30_2023_02_hhm.ffindex"